# Generated by Django 3.1 on 2020-08-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_mijozfikr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamoa',
            name='izox',
        ),
    ]
