# Generated by Django 3.1 on 2020-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_remove_jamoa_izox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(upload_to='rasmlar/maqola_rasm')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='joylashuv_rasm',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='joylashuv_text',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
