# Generated by Django 3.1 on 2020-09-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_auto_20200902_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sarlavha', models.CharField(max_length=500)),
                ('matn', models.TextField()),
            ],
        ),
    ]
