# Generated by Django 3.1 on 2020-09-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0007_yangiliklargayozilish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yangiliklargayozilish',
            name='email',
        ),
        migrations.AddField(
            model_name='yangiliklargayozilish',
            name='e_pochta',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
