# Generated by Django 3.1.1 on 2020-09-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0008_auto_20200904_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mavzu', models.CharField(max_length=100)),
                ('matn', models.TextField()),
            ],
        ),
    ]
